// Copyright 2026 RelyChan Pte. Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package oaschema

import (
	"fmt"

	"github.com/relychan/goutils"
)

const (
	// XRelyServerWeight is the extension name enum for the weight of server if the load balancer is configured.
	XRelyServerWeight = "x-rely-server-weight"
	// XRelyServerHeaders is the extension name enum for custom headers for the server.
	XRelyServerHeaders = "x-rely-server-headers"
	// XRelyServerSecuritySchemes is the extension name enum for server security schemes.
	XRelyServerSecuritySchemes = "x-rely-server-security-schemes"
	// XRelyServerSecurity is the extension name enum for a server security.
	XRelyServerSecurity = "x-rely-server-security"
	// XRelyServerTLS is the extension name enum for a server TLS config.
	XRelyServerTLS = "x-rely-server-tls"
	// XRelyProxyAction is the extension name enum for a proxy action.
	XRelyProxyAction = "x-rely-proxy-action"
	// XRelySecurityCredentials is the extension name enum for security credentials.
	XRelySecurityCredentials = "x-rely-security-credentials"
	// XRelyOAuth2TokenURLEnv is the extension name enum of a custom environment variable for OAuth2 token URL.
	XRelyOAuth2TokenURLEnv = "x-rely-oauth2-token-url-env" //nolint:gosec
	// XRelyOAuth2RefreshURLEnv is the extension name enum of a custom environment variable for OAuth2 refresh URL.
	XRelyOAuth2RefreshURLEnv = "x-rely-oauth2-refresh-url-env"
)

const cookieKey = "cookie"

// SecuritySchemeType represents the authentication scheme enum.
type SecuritySchemeType uint8

const (
	APIKeyScheme SecuritySchemeType = iota
	BasicAuthScheme
	CookieAuthScheme
	HTTPAuthScheme
	OAuth2Scheme
	OpenIDConnectScheme
	MutualTLSScheme
)

var enumSecuritySchemes = []string{
	"apiKey",
	"basic",
	cookieKey,
	"http",
	"oauth2",
	"openIdConnect",
	"mutualTLS",
}

// IsValid checks if the style enum is valid.
func (j SecuritySchemeType) IsValid() bool {
	return j <= 7
}

// String implements fmt.Stringer interface.
func (j SecuritySchemeType) String() string {
	if !j.IsValid() {
		return ""
	}

	return enumSecuritySchemes[j]
}

// MarshalText encodes the receiver into UTF-8-encoded text and returns the result.
func (j SecuritySchemeType) MarshalText() ([]byte, error) {
	return []byte(j.String()), nil
}

// UnmarshalText must be able to decode the form generated by MarshalText.
func (j *SecuritySchemeType) UnmarshalText(text []byte) error {
	result, err := ParseSecuritySchemeType(string(text))
	if err != nil {
		return err
	}

	*j = result

	return nil
}

// MarshalJSON marshals themselves into valid JSON.
func (j SecuritySchemeType) MarshalJSON() ([]byte, error) {
	return goutils.QuoteBytes(j.String()), nil
}

// UnmarshalJSON unmarshals a JSON description of themselves.
func (j *SecuritySchemeType) UnmarshalJSON(input []byte) error {
	value := input[1 : len(input)-1]

	return j.UnmarshalText(value)
}

// SupportedSecuritySchemeTypes return all supported security scheme types.
func SupportedSecuritySchemeTypes() []string {
	return enumSecuritySchemes
}

// ParseSecuritySchemeType parses SecurityScheme from string.
func ParseSecuritySchemeType(value string) (SecuritySchemeType, error) {
	switch value {
	case "apiKey":
		return APIKeyScheme, nil
	case "basic":
		return BasicAuthScheme, nil
	case cookieKey:
		return CookieAuthScheme, nil
	case "http":
		return HTTPAuthScheme, nil
	case "oauth2":
		return OAuth2Scheme, nil
	case "openIdConnect":
		return OpenIDConnectScheme, nil
	case "mutualTLS":
		return MutualTLSScheme, nil
	default:
		return 255, fmt.Errorf(
			"%w; got: %s",
			ErrInvalidSecuritySchemeType,
			value,
		)
	}
}

// ParameterLocation is [the location] of the parameter.
//
// [the location]: https://swagger.io/specification/#parameter-object
type ParameterLocation uint8

const (
	// InQuery is the constant enum that indicates the parameter location in query.
	InQuery ParameterLocation = iota
	// InHeader is the constant enum that indicates the parameter location in header.
	InHeader
	// InPath is the constant enum that indicates the parameter location in path.
	InPath
	// InCookie is the constant enum that indicates the parameter location in cookie.
	InCookie
	// InBody is the constant enum that indicates the parameter location in body.
	InBody
	// InFormData is the constant enum that indicates the parameter location in formData.
	InFormData
)

var enumValueParameterLocations = []string{
	"query",
	"header",
	"path",
	cookieKey,
	"body",
	"formData",
}

// IsValid checks if the style enum is valid.
func (j ParameterLocation) IsValid() bool {
	return j <= 5
}

// String implements fmt.Stringer interface.
func (j ParameterLocation) String() string {
	if !j.IsValid() {
		return ""
	}

	return enumValueParameterLocations[j]
}

// MarshalText encodes the receiver into UTF-8-encoded text and returns the result.
func (j ParameterLocation) MarshalText() ([]byte, error) {
	return []byte(j.String()), nil
}

// UnmarshalText must be able to decode the form generated by MarshalText.
func (j *ParameterLocation) UnmarshalText(text []byte) error {
	result, err := ParseParameterLocation(string(text))
	if err != nil {
		return err
	}

	*j = result

	return nil
}

// MarshalJSON marshals themselves into valid JSON.
func (j ParameterLocation) MarshalJSON() ([]byte, error) {
	return goutils.QuoteBytes(j.String()), nil
}

// UnmarshalJSON unmarshals a JSON description of themselves.
func (j *ParameterLocation) UnmarshalJSON(input []byte) error {
	value := input[1 : len(input)-1]

	result, err := ParseParameterLocation(string(value))
	if err != nil {
		return err
	}

	*j = result

	return nil
}

// ParseParameterLocation parses ParameterLocation from string.
func ParseParameterLocation(input string) (ParameterLocation, error) {
	switch input {
	case "header":
		return InHeader, nil
	case "query":
		return InQuery, nil
	case "body":
		return InBody, nil
	case "path":
		return InPath, nil
	case cookieKey:
		return InCookie, nil
	case "formData":
		return InFormData, nil
	default:
		return 255, fmt.Errorf(
			"%w; got: %s",
			ErrInvalidParameterLocation,
			input,
		)
	}
}

// ParameterEncodingStyle represents the encoding style of the parameter.
// style defines how multiple values are delimited. Possible styles depend on the parameter location – path, query, header or cookie.
type ParameterEncodingStyle uint8

const (
	// EncodingStyleSimple (default of query) comma-separated values. Corresponds to the {param_name} URI template.
	EncodingStyleSimple ParameterEncodingStyle = iota
	// EncodingStyleLabel dot-prefixed values, also known as label expansion. Corresponds to the {.param_name} URI template.
	EncodingStyleLabel
	// EncodingStyleMatrix semicolon-prefixed values, also known as path-style expansion. Corresponds to the {;param_name} URI template.
	EncodingStyleMatrix
	// EncodingStyleForm ampersand-separated values, also known as form-style query expansion. Corresponds to the {?param_name} URI template.
	EncodingStyleForm
	// EncodingStyleSpaceDelimited space-separated array values. Same as collectionFormat: ssv in OpenAPI 2.0.
	// Has effect only for non-exploded arrays (explode: false), that is, the space separates the array values if the array is a single parameter, as in arr=a b c.
	EncodingStyleSpaceDelimited
	// EncodingStylePipeDelimited pipeline-separated array values. Same as collectionFormat: pipes in OpenAPI 2.0.
	// Has effect only for non-exploded arrays (explode: false), that is, the pipe separates the array values if the array is a single parameter, as in arr=a|b|c.
	EncodingStylePipeDelimited
	// EncodingStyleDeepObject simple non-nested objects are serialized as paramName[prop1]=value1&paramName[prop2]=value2&....
	// The behavior for nested objects and arrays is undefined.
	EncodingStyleDeepObject
	// EncodingStyleCookie is analogous to form, but following [RFC6265] Cookie syntax rules,
	// meaning that name-value pairs are separated by a semicolon followed by a single space (e.g. n1=v1; n2=v2),
	// and no percent-encoding or other escaping is applied; data values that require any sort of escaping MUST be provided in escaped form.
	//
	// [RFC6265]: https://datatracker.ietf.org/doc/html/rfc6265#section-4.2.1
	EncodingStyleCookie
)

var enumValueEncodingStyles = []string{
	"simple",
	"label",
	"matrix",
	"form",
	"spaceDelimited",
	"pipeDelimited",
	"deepObject",
	cookieKey,
}

// IsValid checks if the style enum is valid.
func (j ParameterEncodingStyle) IsValid() bool {
	return j < 8
}

// String implements fmt.Stringer interface.
func (j ParameterEncodingStyle) String() string {
	if !j.IsValid() {
		return ""
	}

	return enumValueEncodingStyles[j]
}

// MarshalText encodes the receiver into UTF-8-encoded text and returns the result.
func (j ParameterEncodingStyle) MarshalText() ([]byte, error) {
	return []byte(j.String()), nil
}

// UnmarshalText must be able to decode the form generated by MarshalText.
func (j *ParameterEncodingStyle) UnmarshalText(text []byte) error {
	result, err := ParseParameterEncodingStyle(string(text))
	if err != nil {
		return err
	}

	*j = result

	return nil
}

// MarshalJSON marshals themselves into valid JSON.
func (j ParameterEncodingStyle) MarshalJSON() ([]byte, error) {
	return goutils.QuoteBytes(j.String()), nil
}

// UnmarshalJSON unmarshals a JSON description of themselves.
func (j *ParameterEncodingStyle) UnmarshalJSON(input []byte) error {
	value := input[1 : len(input)-1]

	result, err := ParseParameterEncodingStyle(string(value))
	if err != nil {
		return err
	}

	*j = result

	return nil
}

// ParseParameterEncodingStyle parses ParameterEncodingStyle from string.
func ParseParameterEncodingStyle(input string) (ParameterEncodingStyle, error) {
	switch input {
	case "simple":
		return EncodingStyleSimple, nil
	case "label":
		return EncodingStyleLabel, nil
	case "matrix":
		return EncodingStyleMatrix, nil
	case "form":
		return EncodingStyleForm, nil
	case "spaceDelimited":
		return EncodingStyleSpaceDelimited, nil
	case "pipeDelimited":
		return EncodingStylePipeDelimited, nil
	case "deepObject":
		return EncodingStyleDeepObject, nil
	case cookieKey:
		return EncodingStyleCookie, nil
	default:
		return 255, fmt.Errorf(
			"%w; got: %s",
			ErrInvalidParameterEncodingStyle,
			input,
		)
	}
}
